#extend:
app_name: "og"

logging:
  log_dir: ${join(ROOT, "log")}
  log_filename: ${app_name+".log"}
  log_file: ${join(logging.log_dir, logging.log_filename)}
  format: "%(asctime)s %(levelname)s: %(message)s"
  level: 30
          #CRITICAL = 50
          #FATAL = CRITICAL
          #ERROR = 40
          #WARNING = 30
          #WARN = WARNING
          #INFO = 20
          #DEBUG = 10
          #NOTSET = 0

db:
  db_dir: ${join(ROOT, "db")}
  db_filename: ${app_name+".sqlite"}
  db_file: ${join(db.db_dir, db.db_filename)}

owler:
  url: "https://www.owler.com/"
  login: __FIX_ME__
  password: __FIX_ME__
  


# Funds in millions
funds:
  start: __FIX_ME__
  finish: __FIX_ME__
  gap: __FIX_ME__
  step: __FIX_ME__

year:
  start: __FIX_ME__
  finish: __FIX_ME__
  gap: __FIX_ME__
  step: __FIX_ME__


requests:
  __FIX_ME__